openapi: 3.0.1
info:
  title: Voip
  description: API Definition of Voip
  version: 1.0.0
servers:
- url: http://localhost:8290/
- url: https://localhost:8253/
paths:
  /status/{ticketId}:
    get:
      parameters:
      - name: ticketId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
  /Request:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
